version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Instala dependencias del proyecto...
      - npm install
  pre_build:
    commands:
      - echo Ejecutando pruebas automatizadas...
      - npm run test
  build:
    commands:
      - echo Compilando el proyecto TypeScript con Vite...
      - npm run build
artifacts:
  base-directory: dist
  files:
    - '**/*'